import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { SidebarProvider } from "../components/ui/sidebar";
import { SdSidebar } from "../components/SdSidebar";
import React from "react";
import AuthCheck from "@/components/AuthCheck";
import ThemeProvider from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const userToken = cookieStore.get('userToken')?.value || null;

  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className='flex w-screen bg-[#F5F7F8]'>
              <SdSidebar />
              <div className='flex flex-col w-full '>
                {/* <Navbar /> */}
                <AuthCheck userToken={userToken}>{children}</AuthCheck>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
  {/* <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html></> */}
}